Card-Enabled:
  - 'Viettel'
  - 'Vinaphone'
  - 'Mobifone'
  - 'Vietnamobile'
  - 'Vcoin'
  - 'Zing'
  - 'Gate'

TheSieuToc:
  api-key: ""
  api-secret: ""

MySQL:
  enabled: false
  hostname: "localhost:3306"
  database: ""
  username: "root"
  password: ""

Success-Commands:
  10000:
    - points give %p 10
  20000:
    - points give %p 20
  50000:
    - points give %p 30
  100000:
    - points give %p 100
  200000:
    - points give %p 200
  500000:
    - points give %p 500
  1000000:
    - points give %p 1000

PC-GUI:
  serialInput:
    title: "MineFH"
    input-text: "Nhap so serial vao day"
    left-item:
      enabled: false
      displayName: ""
      lore:
        - "Line 1"
        - "Line 2"
      custom-model-data: 1
  pinInput:
    title: "MineFH"
    input-text: "Nhap ma pin vao day"
    left-item:
      enabled: false
      displayName: ""
      lore:
        - "Line 1"
        - "Line 2"
      custom-model-data: 1