Card-Enabled:
  - 'Viettel'
  - 'Vinaphone'
  - 'Mobifone'
  - 'Vietnamobile'
  - 'Vcoin'
  - 'Zing'
  - 'Gate'

Discount:
  Points-Rate: 1
  Timer: 120 #AS SECOND
  Announce-Messages:
    - "&aMáy chủ hiện đang khuyến mãi &e%s, &ahãy nạp thẻ ngay nhé!"

TheSieuToc:
  api-key: ""
  api-secret: ""

MySQL:
  enabled: false
  hostname: "localhost:3306"
  database: ""
  username: "root"
  password: ""

PC-GUI:
  serialInput:
    title: "MineFH"
    input-text: "Nhap so serial vao day"
    left-item:
      enabled: false
      displayName: ""
      lore:
        - "Line 1"
        - "Line 2"
      custom-model-data: 1
  pinInput:
    title: "MineFH"
    input-text: "Nhap ma pin vao day"
    left-item:
      enabled: false
      displayName: ""
      lore:
        - "Line 1"
        - "Line 2"
      custom-model-data: 1